name: Build docs

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA in https://github.com/typst/typst.
        default: main
        type: string
      docs_base:
        description: |
          The base URL for the documentation. For example, `/` or `/docs/`.
          Refer to typst-docs CLI for more info.
        default: /DOCS-BASE/
        type: string

# This workflow cannot share caches with typst.yaml, because x86_64-unknown-linux-gnu ≠ x86_64-unknown-linux-musl.

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: typst/typst
          ref: ${{ github.event.inputs.ref }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-typst-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-typst
            ${{ runner.os }}-cargo

      - name: Build docs
        run: |
          cargo run --package typst-docs --release -- --assets-dir assets/ --out-file docs.json --base "${{ github.event.inputs.docs_base }}"

      - name: Upload docs.json
        uses: actions/upload-artifact@v4
        with:
          name: docs.json
          path: docs.json
      - name: Upload docs-assets
        uses: actions/upload-artifact@v4
        with:
          name: docs-assets
          path: assets/
